services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
       - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=".:./src"
      - POSTGRES_URI=postgresql+psycopg://postgres:postgres@postgres:5432/authdb
    command: >
      /bin/sh -cx "alembic upgrade head
      && uvicorn --factory src.web:create_app --host 0.0.0.0 --port 8000"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres: