"""deleted row

Revision ID: 24a50faafd3f
Revises: e68603148a67
Create Date: 2024-11-25 20:10:21.296812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24a50faafd3f"
down_revision: Union[str, None] = "e68603148a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.drop_column("users", "is_super_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_super_user", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
